import { FaLinkedin, FaGithub } from "react-icons/fa";
import Navbar from "./components/Navbar";
import "./index.css";


function App() {
  return (
    <>
    <Navbar />
    <div className="app-container">
      <div className="intro-block">
        <h1 className="main-title">Hi, I'm <span className="highlight">Ridhima Pant</span></h1>
        <p className="role-text">2nd Year Computer Science Undergraduate</p> 
        

        <div className="resume-icons">

  <a 
    href="https://www.linkedin.com/in/ridhima-pant-79396931a/" 
    target="_blank" 
    rel="noopener noreferrer" 
    className="icon-link"
  >
    <FaLinkedin size={30} />
  </a>

  <a 
    href="https://github.com/ridhimabrb" 
    target="_blank" 
    rel="noopener noreferrer" 
    className="icon-link"
  >
    <FaGithub size={30} />
  </a>
  
</div> <br />

<h2 className="skills-heading">Skills</h2>

<div className="skills-wrapper">
  {[
    "C, C++ languages",
    "Python, Machine Learning",
    "JavaScript",
    "MySQL, DBMS",
    "HTML & CSS",
    "Vite & React Basics",
    "Figma, Blender"
  ].map((skill, index) => (
    <span key={index} className="skill-pill">{skill}</span>
  ))}
</div>


      </div>
      <section id="projects" className="projects">
        <h3 className="section-title">Some of My Projects</h3>

        <div className="projects-grid">
          <a
           href="https://trading-analyst-hd2do6ygvbeyuw33bjb4nx.streamlit.app/"
           target="_blank"
           rel="noopener noreferrer"
           className="project-card"
         >
           <h3>📌 QuantScope</h3>
           <p>An end-to-end AI-powered trading analysis system that predicts short-term market direction using machine learning and live market data.</p>
         </a>
         <a
           href="https://ridhimabrb.github.io/CrisisMesh/"
           target="_blank"
           rel="noopener noreferrer"
           className="project-card"
         >
           <h3>📌 Crisis Mesh</h3>
           <p>Real-time humanitarian coordination platform connecting disaster victims with responders using Firebase and structured data views.</p>
         </a>
         <a
           href="https://ridhimabrb.github.io/Pixelated/"
           target="_blank"
           rel="noopener noreferrer"
           className="project-card"
         >
           <h3>📌 Pixelated</h3>
           <p>Pixelated is a data-driven emotion journal that transforms daily thoughts into a visual memory archive, analyzing each entry using Hugging Face NLP models </p>
         </a>
         <a
           href="https://ridhimabrb.github.io/Birthday-Cake/"
           rel="noopener noreferrer"
           className="project-card"
         >
           <h3>📌 Birthday Cake</h3>
           <p>Interactive birthday cake where you can light and blow out candles :D</p>
         </a>
         <a
           href="https://ridhimabrb.github.io/Music-FindR/"
           target="_blank"
           rel="noopener noreferrer"
           className="project-card"
         >
           <h3>📌 Music FindR</h3>
           <p>Enter an artist's name to see all their albums and release dates, and play on Spotify</p>
         </a>
         <a
           href="https://ridhimabrb.github.io/K-Nearest-Neighbors-Model/"
           target="_blank"
           rel="noopener noreferrer"
           className="project-card"
         >
           <h3>📌 KNN Algorithm Visualizer</h3>
           <p>A p5.js interactive project that performs k-nearest neighbors classification based on your cursor position</p>
         </a>

        </div>
      </section>
      
      <section id="writing" className="section writing-section">
       <h2 className="section-title">Writing</h2>
       <p >Ever since I can remember, writing has been an integral part of my life. <br /> Be it essays, journal entries, poems, news articles, I genuinely enjoy doing it all.<br /> I got a poetry book published in 2020 and have a writing blog I started in 2019 linked here!</p>
       <a 
         href="https://www.amazon.in/Heart-Head-Hand-Ridhima-Pant/dp/9390468159" 
         target="_blank"
         rel="noopener noreferrer"
         className="fancy-btn"
       >
         BOOK LINK
       </a> <br /><br />
       <a 
         href="https://pantridhima2323.wixsite.com/goldclouddiaries" 
         target="_blank"
         rel="noopener noreferrer"
         className="fancy-btn"
       >
         BLOG LINK
       </a>
       <h2>Article- Everyone needs to get more Anti-AI right away</h2>
       <p>The forced inclusion of AI in every sphere of life is now not only frustrating but terrifying too. On November 20, 2025 Google launched Nano Banana Pro, an AI image generation tool. I had been meaning to write on my disfavour of artificial intelligence since long, but seeing the images generated by Nano Banana Pro and people's reactions to it was really the trigger. Artificial intelligence is an asset to society only for as long as it is used advantageously and with decent intentions. And to think that is possible in today's world would be foolishness. <br />


So basically, the images generated by Nano Banana Pro are so realistic you cannot distinguish them from a real photograph. Bottomline, the age of photogenic evidence is over. The smooth texture that helped us identify artificially generated images is GONE now. I think not everyone is comprehending how crazy this is and the downside it comes with. We have reached that point where we straight up won't be able to distinguish a fake image from a real one. Someone could generate a believable photo of you without consent and you'd be helpless as there's no proof really of it being fake. And people would BELIEVE it. Not just at personal level, this is menacing at professional level too. There should be calculated laws against this at this point. <br /><br />


I saw a tweet that read "time to start making a serious plan for the future to be off my phone in a major way" and valid thought but it isn't really affordable, hell we shouldn't have even reached this point. With the amount of digital footprint everyone has these days, no one really is safe lol (I tried downplaying it with lol but the gravity of the situation is unexplainable). What is even scarier is how fast these advancements are happening. Just last year AI used to generate images with 6 fingers in one hand and typos in every word. At this rate, by next year there will be whole videos that are gonna be indistinguishable. All AI tools should have mandatory watermarks. I'll die on this hill. And SynthID (a hidden watermark) does exist but it only works for content generated by Google AI. So it's not viable. Plus no one is gonna crosscheck every piece of content they come across for a hidden watermark. <br />

 

Last week in the news, there was this Pakistani newspaper that left their AI prompt in the article by mistake and it got printed along with the news. Firstly, yes, how stupid can someone be, but 2. NEWSPAPERS WERE SUPPOSED TO BE TYPED BY HAND, using PRIMARY INFORMATION. It was one of those few enduring things left. And I get that AI would help you complete the work faster so it's convenient but you probably CHOSE that profession?? Do you not like writing enough to write one article for your job.. This might soon become Lost Art. Which reminds me of another tweet I saw where a sketch artist was feeling distraught and helpless as their customer demanded refund because their drawing was "too good". It was too good and they were being accused of using AI. Well that is bound to happen with the amount of media we supply to AI, it's getting better/ more humanlike at everything it does. How sad it is that legitimate artists are now doubted and will soon get replaced. <br /><br />


Surely a coin has 2 sides, but we've now lost control of AI. I have seen so many studies on how LLMs like ChatGPT are weakening cognitive skills like critical thinking and memory and making people lazier. The fact that there exists AI for converting an AI written article/ homework to sound like it was written by a human in order to surpass AI detection tools is so ironic and mind boggling. <br />

We are doomed. Everyone needs to get more Anti-AI right away.</p>
     </section>

     <section id="photography" className="section photography-section">
      <h2 className="section-title">Photography</h2>

      <div className="photo-grid">
        
        <img src={`${import.meta.env.BASE_URL}2.JPG`} alt="" />
        <img src={`${import.meta.env.BASE_URL}1.JPG`} alt="" />
        <img src={`${import.meta.env.BASE_URL}3.JPG`} alt="" />

      </div>

      <a 
        href="https://www.instagram.com/shutteridhima/?utm_source=ig_web_button_share_sheet" 
        target="_blank"
        rel="noopener noreferrer"
        className="fancy-btn"
      >
        PHOTOGRAPHY ACCOUNT
      </a>
    </section>




      {/* Footer With Handwriting */}
      <footer className="footer">
        <p className="footer-main handwriting">A tiny digital corner of my mind,   by Ridhima Pant</p>
        <p className="font-note handwriting small-note">This font is actually my handwriting!</p>
      </footer>
    </div>
    </>
  );
}

export default App;
